backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - label: "Startseite"
        name: "startseite"
        file: "content/pages/index.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }
